//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdsgames.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLLOW
    {
        public int FOLLOWID { get; set; }
        public int USERID { get; set; }
        public int FRIENDID { get; set; }
        public string SFB1 { get; set; }
        public string SFB2 { get; set; }
        public string SFB3 { get; set; }
        public string SFB4 { get; set; }
        public string SFB5 { get; set; }
        public string SFB6 { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
