//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdsgames.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUID
    {
        public int ID { get; set; }
        public int FRIENDID { get; set; }
        public bool BLOCK { get; set; }
        public int USERID { get; set; }
        public int Confirmed { get; set; }
        public int Request { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
