//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdsgames.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCLT
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int MLSID { get; set; }
        public string URL { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual MSLID MSLID { get; set; }
    }
}
