//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdsgames.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.FUIDs = new HashSet<FUID>();
            this.FUIDs1 = new HashSet<FUID>();
            this.UCLTs = new HashSet<UCLT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime DOB { get; set; }
        public string EMAIL { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string STATE_PROVINCE { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<decimal> USERTYPE { get; set; }
        public Nullable<bool> BAN { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> LASTONDATE { get; set; }
        public byte TermsAgree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUID> FUIDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUID> FUIDs1 { get; set; }
        public virtual LVIDEO LVIDEO { get; set; }
        public virtual SECURITY SECURITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UCLT> UCLTs { get; set; }
    }
}
