//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdsgames.com.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UsersDatabaseEntities_QDSGames : DbContext
    {
        public UsersDatabaseEntities_QDSGames()
            : base("name=UsersDatabaseEntities_QDSGames")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FOLLOW> FOLLOWs { get; set; }
        public virtual DbSet<FUID> FUIDs { get; set; }
        public virtual DbSet<LVIDEO> LVIDEOs { get; set; }
        public virtual DbSet<SECURITY> SECURITies { get; set; }
        public virtual DbSet<UCLT> UCLTs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<MSLID> MSLIDs { get; set; }
    
        public virtual ObjectResult<GetUserSearchAll_Result> GetUserSearchAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserSearchAll_Result>("GetUserSearchAll");
        }
    
        public virtual ObjectResult<GetAllUsers_Result> GetAllUsers(Nullable<int> iDIn)
        {
            var iDInParameter = iDIn.HasValue ?
                new ObjectParameter("IDIn", iDIn) :
                new ObjectParameter("IDIn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUsers_Result>("GetAllUsers", iDInParameter);
        }
    
        public virtual ObjectResult<SearchUser_Result> SearchUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchUser_Result>("SearchUser", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetFriends(Nullable<int> userIDs)
        {
            var userIDsParameter = userIDs.HasValue ?
                new ObjectParameter("userIDs", userIDs) :
                new ObjectParameter("userIDs", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetFriends", userIDsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetUserID(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetUserID", usernameParameter);
        }
    
        [DbFunction("UsersDatabaseEntities_QDSGames", "GetUserFriends")]
        public virtual IQueryable<GetUserFriends_Result> GetUserFriends(Nullable<int> userIDs)
        {
            var userIDsParameter = userIDs.HasValue ?
                new ObjectParameter("userIDs", userIDs) :
                new ObjectParameter("userIDs", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetUserFriends_Result>("[UsersDatabaseEntities_QDSGames].[GetUserFriends](@userIDs)", userIDsParameter);
        }
    }
}
